
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 123456
  host: localhost
  port: 5432
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: ypill_production

test:
  <<: *default 
  database: ypill_test


production:
  <<: *default
  database: ypill_production
  username: postgres
  #password: 123456'
